### ISSUE TITLE
Different result count depending on order

### ISSUE THREAD

**Issue by m-kus** [blockwatch-cc/tzindex#1]
https://api.tzstats.com/tables/income?address=tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1&columns=cycle  // 142 items

https://api.tzstats.com/tables/income?address=tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1&columns=cycle&order=desc  // 140 items

**Comment by echa** [comment]
This should be fixed in the latest version. Please re-open if the problem persists.

**Comment by m-kus** [comment]
It works, thank you!
