### ISSUE TITLE
Missing transaction in account endpoint(?)

### ISSUE THREAD

**Issue by Felix0301** [blockwatch-cc/tzindex#16]
Dear TzIndex (and I assume TzStats) team,

The endpoint: 
https://api.tzstats.com/explorer/account/tz1f4fSycx5gutm4Vn4QqwD7yVcThSY9uYaR/op 
seems to be missing an operation:
https://api.tzstats.com/explorer/op/ooH7rtYU4axSv23EoSgYynh1rR85xTPTcwyQ2MhzE7NUqK2Fnmc

Am I using the API incorrectly or is it a bug?

Thanks!

**Comment by echa** [comment]
This was a classical off-by-one bug we had introduced with a recent optimization. Should be fixed now. Thanks for reporting!
