### ISSUE TITLE
Not all transactions in block returned, due to default limit

### ISSUE THREAD

**Issue by kolya182** [blockwatch-cc/tzindex#17]
`Query`:  https://api.tzstats.com/explorer//block/882580/op
`Expected result`: Return all ops associated with block
`Actual result` Only 20 out of 31 returned
`Desire solution`: Return all ops by default (there not that many anyway)
`Current hack`: Supply `limit=<wahtever_big_numebr_in_mind>`

I understand reason to apply limit when query something like https://api.tzstats.com/explorer/account/tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK/op?order=desc&type=transaction,delegation&limit=24

@echa What do you think ?

**Comment by echa** [comment]
Its an operational decision to limit bandwidth and query processing times for simple use-cases on our free API service. Tezos has seen blocks with up to 2500 operations and the median block size is expected to grow.

On `/explorer` endpoints the default limit for lists is 20, max limit 100. You can set these limits via `TZ_SERVER_DEFAULT_EXPLORE_COUNT` and `TZ_SERVER_MAX_EXPLORE_COUNT` when running our indexer yourself. Alternatively I suggest you use the different `/tables` endpoints which are more efficient and have higher limits (500 default). Tables also allow you to pick the columns you actually need which saves everybody bandwidth and processing time.

Example to fetch all transactions in a block with columns of interest

```
GET /tables/op?block={height|hash|head}&columns=hash,type,sender,receiver,volume,fee,status&type=transaction&limit=5000
```

Hint: you way want to use block hashes to be reorg safe.

**Comment by kolya182** [comment]
> Its an operational decision to limit bandwidth and query processing times for simple use-cases on our free API service. Tezos has seen blocks with up to 2500 operations and the median block size is expected to grow.
> 
> On `/explorer` endpoints the default limit for lists is 20, max limit 100. You can set these limits via `TZ_SERVER_DEFAULT_EXPLORE_COUNT` and `TZ_SERVER_MAX_EXPLORE_COUNT` when running our indexer yourself. Alternatively I suggest you use the different `/tables` endpoints which are more efficient and have higher limits (500 default). Tables also allow you to pick the columns you actually need which saves everybody bandwidth and processing time.
> 
> Example to fetch all transactions in a block with columns of interest
> 
> ```
> GET /tables/op?block={height|hash|head}&columns=hash,type,sender,receiver,volume,fee,status&type=transaction&limit=5000
> ```
> 
> Hint: you way want to use block hashes to be reorg safe.

`block` doesn't seem to be part of query: https://tzstats.com/docs/api/index.html#table-endpoints
https://api.tzstats.com/tables/op?block=883861&columns=hash&type=transaction&limit=5000&order=desc
```js
{
  "errors": [
    {
      "code": 1007,
      "status": 400,
      "message": "incorrect request syntax",
      "scope": "StreamTable",
      "detail": "unknown column 'block'",
      "request_id": "BW-955fddc34d6c3d32946ce7d93e3d41d8e8bc5df9"
    }
  ]
}
```
