### ISSUE TITLE
Docs typo and wrong type for errors property with actual response

### ISSUE THREAD

**Issue by kolya182** [blockwatch-cc/tzindex#18]
From docs https://tzstats.com/docs/api/index.html#operations, endpoint https://api.tzstats.com/explorer/account/tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK/op?order=desc&type=transaction,delegation&limit=250 response errors as an `array`, but in docs described as an `object`

![](https://cdn.discordapp.com/attachments/605407881944367125/692882899111772220/Screen_Shot_2020-03-26_at_4.46.37_PM.png)

**Comment by echa** [comment]
Fixed. Thanks for reporting.
