### ISSUE TITLE
"block" parameter has no effect on `/explorer/contract/ID/calls`

### ISSUE THREAD

**Issue by xplat** [blockwatch-cc/tzindex#20]
Choosing an example contract that was recently active on Carthagenet, https://api.carthagenet.tzstats.com/explorer/contract/KT1CUTjTqf4UMf6c9A8ZA4e1ntWbLVTnvrKG/calls?prim=true&order=desc&limit=100 gives the same JSON result as https://api.carthagenet.tzstats.com/explorer/contract/KT1CUTjTqf4UMf6c9A8ZA4e1ntWbLVTnvrKG/calls?prim=true&order=desc&limit=100&block=BLNXc4JnUyjMh14KdTqcsJRqRkBs5LVSJiYPvZnfExMLrwHqRyL and https://api.carthagenet.tzstats.com/explorer/contract/KT1CUTjTqf4UMf6c9A8ZA4e1ntWbLVTnvrKG/calls?prim=true&order=desc&limit=100&block=331300 ...

**Comment by echa** [comment]
Ouch. Optimization bug. The `block` param should work as expected now. Code in this repo did not have the issue.
