### ISSUE TITLE
BuildType in primitives.go

### ISSUE THREAD

**Issue by sebeec** [blockwatch-cc/tzindex#23]
I was re-using this code. Thanks a lot. great work!

Some of the cases in the BuildType function in [primitives.go](https://github.com/blockwatch-cc/tzindex/blob/master/micheline/primitives.go) do not correctly pass values.

E.g. PrimInt, PrimString, and PrimBytes. Should be something like:
```
	case PrimInt:
		t.OpCode = p.Type.TypeCode()
		t.Type = PrimNullary
		t.Int = p.Int

	case PrimString:
		t.OpCode = p.Type.TypeCode()
		t.Type = PrimNullary
		t.String = p.String

	case PrimBytes:
		t.OpCode = p.Type.TypeCode()
		t.Type = PrimNullary
		t.Bytes = p.Bytes
```

**Comment by echa** [comment]
Thanks, but adding values (i.e. `t.Int = p.Int`) is not intended here.

`BuildType()` is meant to construct a type definition based on values, but returned primitives are not supposed to contain any values. When you output the type tree it has the same structure as as a normal type definition in a Michelson script.

We use BuildType only to construct a conforming type tree for packed data (PACK does not store type info currently) which can later be used to process unpacked values in the same way we process normal values.

**Comment by sebeec** [comment]
Thanks echa, for the clarification. I was expecting something else, since I was using it differently.

**Comment by echa** [comment]
Can you explain your use case? We're working on a separate Go library that's supposed to contain these building blocks in a composable way.
