### ISSUE TITLE
larger-than-documented RAM usage

### ISSUE THREAD

**Issue by xplat** [blockwatch-cc/tzindex#27]
With the blockwatch/tzindex:v6.0.2-6-g69ae9fe docker image on carthagenet and an existing database that's fairly up to date (last Wednesday at least) the tzindex process will use 30+GB within a couple of minutes after startup (couldn't measure it precisely since the machine i'm running it on doesn't have enough RAM to get to a steady state).  The README says 4-16GB required.  It also claims to be tunable but so far I have been able to find a setting that has a significant effect either direction that I can detect.

**Comment by echa** [comment]
That is much to high, let's investigate. For reference, the Carthagenet indexer on our server uses 4.4GB RAM right now and all db files combined are 709MB in size. 

How large are your database files? Can you please post responses from the following calls: 

- `GET /system/tables`
- `GET /system/mem`

**Comment by echa** [comment]
Update: I just did a fresh sync and starting after block 397,936 there seems to be an issue with bigmap copy operations that lets the bigmap index grow too fast. I'll investigate further.

**Comment by echa** [comment]
I just published v6.0.3 that should fix this issue. Underlying reason was an unintended side-effect of bigmap copies in combination with temporary bigmaps (something we lacked test cases for until this week). 

I suggest a database rebuild from scratch because your bigmap table may have grown very large and table cleaning would take longer than a rebuild.

**Comment by xplat** [comment]
Thanks, this was a very prompt fix!  Newly synced instance is running happily with 1.4GB of resident memory ...

**Comment by echa** [comment]
Happy it works! Most of the other remaining bigmap issues will go way with the next major release (but as unpleasant side-effect that also comes with a few small API changes, so your tooling may be impacted, but not much). I just have to find some time to merge and test everything.
