### ISSUE TITLE
Incorrect balances for the Foundation contracts

### ISSUE THREAD

**Issue by m-kus** [blockwatch-cc/tzindex#3]
There are 16 smart contracts without origination operations that are delegated to TF bakers. Their balances are null in tzstats:
https://api.tzstats.com/tables/snapshot?address=KT1Msatnmdy24sQt6knzpALs4tvHfSPPduA2&columns=balance,delegate,cycle&order=desc&is_selected=1

'KT1TcAHw5gpejyemwRtdNyFKGBLc4qwA5gtw',
'KT1VsSxSXUkgw6zkBGgUuDXXuJs9ToPqkrCg',
'KT1Um7ieBEytZtumecLqGeL56iY6BuWoBgio',
'KT1THsDNgHtN56ew9VVCAUWnqPC81pqAxCEp',
'KT1RUT25eGgo9KKWXfLhj1xYjghAY1iZ2don',
'KT1Q1kfbvzteafLvnGz92DGvkdypXfTGfEA3',
'KT1FuFDZGdw86p6krdBUKoZfEMkcUmezqX5o',
'KT1CSKPf2jeLpMmrgKquN2bCjBTkAcAdRVDy',
'KT1WPEis2WhAc2FciM2tZVn8qe6pCBe9HkDp',
'KT1FN5fcNNcgieGjzxbVEPWUpJGwZEpzNGA8',
'KT1QuofAgnsWffHzLA7D78rxytJruGHDe7XG',
'KT1SLWhfqPtQq7f4zLomh8BNgDeprF9B6d2M',
'KT1PDAELuX7CypUHinUgFgGFskKs7ytwh5Vw',
'KT1Cz7TyVFvHxXpxLS57RFePrhTGisUpPhvD',
'KT1A56dh8ivKNvLiLVkjYPyudmnY2Ti5Sba3',
'KT1EWLAQGPMF2uhtVRPaCH2vtFVN36Njdr6z'

**Comment by echa** [comment]
Fixed now. The snapshot did not include the unclaimed balances of vesting contracts. Now it does. Update requires database rebuild.
