### ISSUE TITLE
out of sync 6.0.3

### ISSUE THREAD

**Issue by smithy9901** [blockwatch-cc/tzindex#30]
stopped at an altitude: 984006

config.json
`{
        "server": {
                "addr": "0.0.0.0",
                "port": 8000,
                "scheme": "http",
                "host": "127.0.0.1",
                "workers": 50,
                "read_timeout": "5s",
                "header_timeout": "10s",
                "write_timeout": "1000s",
                "keepalive": "90s",
                "shutdown_timeout": "15s",
                "max_list_count": 50000,
                "default_explore_count": 20,
                "max_explore_count": 100,
                "cors_enable": false,
                "cors_origin": "*",
                "cors_allow_headers": "Authorization, Accept, Content-Type, X-Api-Key, X-Requested-With",
                "cors_expose_headers": "Date, X-Runtime, X-Request-Id, X-Api-Version",
                "cors_methods": "GET, OPTIONS",
                "cors_maxage": "86400",
                "cors_credentials": "true",
                "cache_enable": false,
                "cache_control": "public"
        },
        "crawler": {
                "queue": 1000,
                "snapshot_path": "./db/xtz/snapshots",
                "snapshot_blocks": [],
                "snapshot_interval": 0
        },
        "database": {
                "path": "./db/xtz",
                "engine": "bolt",
                "gc_interval": 50000000,
                "gc_ratio": 1.0,
                "log_slow_queries": "2s",
                "account": {
                        "cache_size": 4
                },
                "account_index":{
                        "cache_size": 8
                },
                "contract": {
                        "cache_size": 2
                },
                "contract_index":{
                        "cache_size": 2
                },
                "op": {
                        "cache_size": 4
                },
                "op_index":{
                        "cache_size": 128
                },
                "block": {
                        "cache_size": 8
                },
                "block_index":{
                        "cache_size": 64
                },
                "flow": {
                        "cache_size": 4
                },
                "supply": {
                        "cache_size": 2
                },
                "chain": {
                        "cache_size": 2
                },
                "right": {
                        "cache_size": 2
                },
                "income": {
                        "cache_size": 2
                }
        },
        "rpc": {
                "host": "127.0.0.1",
                "port": 8732,
                "threads": 10,
                "disable_tls": true,
                "dial_timeout": "20s",
                "keepalive": "30m",
                "idle_timeout": "30m",
                "response_timeout": "60s",
                "continue_timeout": "60s",
                "idle_conns": 50
        },
        "logging": {
                "backend": "stdout",
                "flags": "date,time,micro,utc",
                "level": "info",
                "blockchain": "info",
                "database": "info",
                "rpc": "info",
                "server": "debug",
                "report": "info",
                "micheline": "info"
        }
}`

There is something not clear in the logs

`363436327451000231000c000000383130303030303030303000000435353700440000000230002600000062747a314c6b4579426139375568795a6a485059505532705648714472353770524c654161000231000b0000003630303630303030303000000435353800440000000230002600000062747a314c6b475259664d6957783768747161505937676738743278516679744567514b44000231000b0000003231373837353030303000000435353900430000000230002600000062747a314c6b4a35614155344662476e664a4a7459766a6e7839473662624d5872536e5843000231000a00000035323530303030303000000435363000440000000230002600000062747a314c6b4e764c5a3171446475727370716d4d595a5a763861357a747155505a733847000231000b0000003330303030303030303000000435363100440000000230002600000062747a314c6b504e7a4457484d6376337846695a697669704247684b587a466d7758484878000231000b0000003234323539353432333000000435363200440000000230002600000062747a314c6b50727831586f346e6568684771694d576b616f774831545a4d35686b45484c000231000b0000003231363730393537303500000435363300440000000230002600000062747a314c6b5331787278664b786470326a486a6237594b78585a5a453458416859444137000231000b0000003437393530333530303000000435363400440000000230002600000062747a314c6b54555065326974486654653456694d47755a3541615275644863455974356e000231000b0000003630303030303030303000000435363500440000000230002600000062747a314c6b55535741696a41785a41423477315a565246375942384a566f614c75524643000231000b0000003537333835303030303000000435363600430000000230002600000062747a314c6b556a39666831774874436e314d4d584d766e37383852793247546f61323377000231000a00000038363930343636383300000435363700430000000230002600000062747a314c6b564c7956673535433945686e384d4d785668435a66416a6762563876677469000231000a00000035353335383736393200000435363800430000000230002600000062747a314c6b566e734341397867316e577334346a774268643865565371466f507a666161000231000a00000035373630343333343000000435363900440000000230002600000062747a314c6b5853363337596179453342484c4861685757354a46797877766457484b546e000231000b0000003133383039323939343000000435373000440000000230002600000062747a314c6b594773736f4645657237794c5a665367516a635a4166663347447a52733277000231000b0000003132313934313537363000000435373100440000000230002600000062747a314c6b63745731666b6a333373534e7347567755326a4e435143337a455265346b51000231000b0000003632363031343336323000000435373200420000000230002600000062747a314c6b67344c6379326e426e78334433624376763578757161386245615670454a710002310009000000363338343539393700000435373300440000000230002600000062747a314c6b6869624c4b6175724746563358487766474b685833324e4869525264727674000231000b0000003231363935393931303000000435373400430000000230002600000062747a314c6b69425336794b7976576667357052734236386d79696f66525633536375436f000231000a00000034313937373530303000000435373500430000000230002600000062747a314c6b6a6755344a4362666d6834483932717154534b55697337767147456a4e6539000231000a00000035303030303030303000000435373600430000000230002600000062747a314c6b6b375266364e71686a375739636d526b62787166536b367757637669557231000231000a00000036383631333832323000000435373700440000000230002600000062747a314c6b6d4a5a664433565239595842635363316f7a62384232643677626e70457647000^C`

**Comment by echa** [comment]
This may have been fixed in 95156a8, please try the current master branch.

**Comment by smithy9901** [comment]
Can't you make the tag 6.0.3-fix pls?

**Comment by echa** [comment]
Sure, its 6.0.4

**Comment by smithy9901** [comment]
thx
