### ISSUE TITLE
Support for edo protocol

### ISSUE THREAD

**Issue by bkontur** [blockwatch-cc/tzindex#32]
Hello, I would like to ask, when will be release new docker with 008 edo protocol support,
now it fails like this on edonet:

```
2021/01/21 21:15:35.415749 ERRO BLOC Processing block 184 BLLT8xpajb4hPVU64VsmD7iFhHRmBLDYb27wRoBrATjk5GVLXdP: build stage 3: origination op [3:0:1]: patch bigmap: bigmap patch unknown contract KT1A4mDg25qvC3tcwyNFy87kcCpLNyfvop2M
2021/01/21 21:15:35.420797 INFO BLOC Stopping blockchain sync due to too many errors at 183.
```

**Comment by echa** [comment]
Closing this as Edo protocol detection, constants, voting and format changes are supported now. A few issues remain regarding the unwrapping of comb pairs, but this unfortunately requires more work.

**Comment by bkontur** [comment]
thank you, working now
