### ISSUE TITLE
Tzindex does not read rpc values from config file

### ISSUE THREAD

**Issue by elmagrinmint** [blockwatch-cc/tzindex#36]
I modified my config file with a custom rpc  path like below

```
"rpc": {
		"host": "http://192.168.64.2",
		"port": 31840,
		"threads": 2,
		"disable_tls": true,
		"dial_timeout": "10s",
		"keepalive": "30m",
		"idle_timeout": "30m",
		"response_timeout": "60s",
		"continue_timeout": "60s",
		"idle_conns": 2

...
```

When I execute the following commands:

`./tzindex run` or `./tzindex run -c config.json` 

it still does not switch the rpc. I get 
![Screenshot 2021-06-09 at 11 43 49](https://user-images.githubusercontent.com/52529310/121332236-f6624c00-c917-11eb-87a5-4113967697aa.png)

I know its accessing the right json file

**Comment by echa** [comment]
Thanks for reporting! The problem was that the `--rpcurl` command line argument's default was overwriting everything else. Fixed on the latest master branch.
