### ISSUE TITLE
Cannot access tzindex server

### ISSUE THREAD

**Issue by elmagrinmint** [blockwatch-cc/tzindex#37]
When I launch tzindex, I cannot access it:

![Screenshot 2021-06-09 at 11 44 46](https://user-images.githubusercontent.com/52529310/121332382-18f46500-c918-11eb-9e04-868ea6c54868.png)

![Screenshot 2021-06-09 at 11 45 13](https://user-images.githubusercontent.com/52529310/121332434-290c4480-c918-11eb-8528-e23568a4010a.png)

As such I amnot able to connect tzstats to it. Is a further config required?

**Comment by echa** [comment]
There is nothing behind the `/` URL. Try `/explorer/tip` for example. The full API docu is at https://tzstats.com/docs/api
