### ISSUE TITLE
Is baker capacity accurate in V12?

### ISSUE THREAD

**Issue by gbataille** [blockwatch-cc/tzindex#39]
Hi all,

I was looking at the baker capacity logic in v12 for my project, and I could not get my numbers to "match" those on tzstats.
After finding this code, I'm unsure what the logic is

If we look just at the v12 code
```go
func (b Baker) StakingCapacity(p *tezos.Params, netRolls int64) int64 {
	[...]

    // 10% of staking balance must be locked
    // deposit = stake * frozen_deposits_percentage / 100
    // max_stake = total_balance / frozen_deposits_percentage * 100
    // max_delegation = max_stake - total_balance
    deposit_cap := util.Min64(b.DepositsLimit, b.TotalBalance())
    if deposit_cap < 0 {
        deposit_cap = b.TotalBalance()
    }
    return deposit_cap*100/int64(p.FrozenDepositsPercentage) - b.TotalBalance()
}
```

I understand `deposit_cap` which is the max a baker is willing / can deposit.

Then `deposit_cap*100/int64(p.FrozenDepositsPercentage)` makes sense as the max stake the baker represents I guess.

But then `b.TotalBalance()` is subtracted from it. I can make sense of that. The baker's balance participates in the total stake it represents, but if you want to know its capacity to accept delegates, then you have to remove the baker's funds. I'm ok if that's how `StakingCapacity` is defined

But then the tzstats website, to show the available capacity, seems to do
`StakingCapacity - StakingBalance` with `StakingBalance` including the baker's balance. 
(https://github.com/blockwatch-cc/tzstats/blob/ee6e347a074600ca1e60b53b364ec477ad906bc5/src/components/Accounts/AccountInfo/AccountInfo.js#L153)
It seems to me that the baker balance is subtracted twice resulting in an overestimation of the used capacity.

I must say I don't know very well everything, and obviously the v12 logic is very new but something feels not right to me. Could you please let me know if I'm missing something

Let me try to make it clearer with an example directly from tzstats, extracting the baker json (truncated)
```json
{
    "address": "tz1d6Fx42mYgVFnHUW8T8A7WBfJ6nD9pVok8",
    "baker_since": "2018-09-25T12:49:55Z",
    "grace_period": 475,
    "baker_version": "61fed540",
    "total_balance": 113277.444274,
    "spendable_balance": 388.453791,
    "frozen_balance": 112888.990483,
    "delegated_balance": 1030292.164604,
    "staking_balance": 1143569.608878,
    "staking_capacity": 1019496.998466,
    "deposits_limit": null,
}
```

`staking_capacity` is `10 * total_balance - total_balance`, consistent with the tzindex code above
But then, this baker shows a free capacity of `-124,073 XTZ` in the front end, which is `staking_capacity - staking_balance`, thus discounting twice the baker's `total_balance`, right?

**Comment by echa** [comment]
Hey! So the capacity under Ithaca is defined by 10x the baker's deposit. Other than before (see here https://tzstats.com/docs/guide/page/formulas/#baker-capacity) we now subtract the baker's own balance from the capacity to show how much free space is actually available. Arguably the term `capacity` is no longer correct, I'll think about this and may revert the subtraction (and do it on the frontend instead).

The tzstats repo is actually the old v1 of the explorer which is no longer in use (sorry for the confusion, I should set that one to archived). The site today shows the direct values `staking_balance` and `staking_capacity` as reported by the current API.

**Comment by gbataille** [comment]
wait, for the API payload above, this is what the site shows

https://tzstats.com/tz1d6Fx42mYgVFnHUW8T8A7WBfJ6nD9pVok8
![image](https://user-images.githubusercontent.com/1113065/161989192-3fb77152-9397-4aa0-8954-fe007e03b80a.png)

the "capacity" (-124073) is `staking_capacity` (where the baker balance is not included) minus `staking_balance` where the baker balance is included. Thus removing the balance twice, no?

I'm sorry but I'm just struggling there :)

**Comment by echa** [comment]
What's displayed as 'free capacity' is `staking_capacity - staking_balance` from the API. And yes you are right that this is wrong since `staking_capacity` has already been reduced by `total_balance` on the API side. 

We're going to deploy new backends today where this issue will be fixed. The API will then no longer subtract total_balance from staking_capacity. 

Thanks for bringing this up! Much appreciated.

**Comment by echa** [comment]
This has been fixed in tzindex and our public API. Feel free to reopen if you find more discrepancies. It's likely there are other issues with the new active stake calculations.

**Comment by gbataille** [comment]
Awesome. That means I'm not crazy ;)

Thanks for the prompt answer and fix
