### ISSUE TITLE
API endpoint for current and historical prices of FA1.2 and FA2 tokens

### ISSUE THREAD

**Issue by BearCooder** [blockwatch-cc/tzindex#43]
Hi I I would like to add my "idea" for an API endpoint for tezos token prices.

So for FA2 and FA1.2 tokens there is no endpoint to get historical price or "live" price.
The API endpoint should allow to query tokens using the contract address which is unique to a given token.

Knowing the contract address for youves uUSD
KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW

I should be able to query with Tzstats and get the current prices

Now the question some might ask is "But there are more decentralised exchanges so there are different prices, how to do that?"

A very good example is how coingecko does it. They have a separate object for every exchange they gather/track the data.

I dont say Tzstats api should track every dex. But for example the top 2-3?

then you would have something like this:

{
Quipu:{
   "base": "uUSD",
   "target": "XTZ",
   "lastprice": 1,
   "volume": "157824452",
   "bid_ask_spread_percentage": "0.2",
   "timestamp": "2022-04-27T21:10:16+00:00",
   "last_trade_at": "2022-04-26T21:10:16+00:00",
   "trade_url": "quipuswap dot com/pair"
      }
Spicy:{
  "base": "uUSD",
   "target": "XTZ",
   "lastprice": 1,
   "volume": "157824452",
   "bid_ask_spread_percentage": "0.2",
   "timestamp": "2022-04-27T21:10:16+00:00",
   "last_trade_at": "2022-04-26T21:10:16+00:00",
   "trade_url": "spicyswap dot com/pair"
      }
}```

Then people can easily get the data and build on top of it.
Since a year people are hoping for coingecko, cmc api but lets dont wait and integrate this for Tzstats. 🙂

My example screenshot is taken from this example here.
https://api.coingecko.com/api/v3/coins/ethereum/contract/0x0d8775f648430679a709e98d2b0cb6250d2887ef

The screenshot 
![grafik](https://user-images.githubusercontent.com/104575503/165767759-4ff131da-e65f-46ad-a0d0-954e67478efc.png)

**Comment by echa** [comment]
I saw your discussion on the baking bad repo. Its a great feature idea, but expensive to implement and somewhat expensive to host that data. Quick bizdev question before we engage any further, how much would you be willing to pay for such a feature, say as monthly subscription.

**Comment by Reudlak** [comment]
I assume that the hurdles you mention - expensive to implement and somewhat expensive to host - are the reason why there is no possibility to track token prices in tezos defi and thus no real tools built on top of it.

I am currently building a product myself and stumbled accross this "problem", thats why I did propose it. I would be more than willing to pay for such a feature on a monthly subscription and I am sure many more other projects/services would be too as thats a real lacking piece in the ecosystem. When it comes to the price to be honest I dont know what a fair price would be so hard for me to throw in random amounts. I dont know €50 as monthly fee? I suppose it depends on the number of calls or the amount of data I can query from the API and if its a commercial license too so please take this a a big guess. With a short explainer about the pricing it can be more too.

**Comment by BearCooder** [comment]
Is there any update on this? @echa Maybe make a survey to gather interest if you are not convinced about this feature

**Comment by echa** [comment]
This will be available when our token indexer is done. Probably a private/paid subscription though and not part of tzindex.

**Comment by BearCooder** [comment]
Sure private/paid feature sounds great, looking forward to an announcement!

**Comment by echa** [comment]
This is available as private beta right now. Please send me an email if you're still interested.
