### ISSUE TITLE
Cannot kill tzindex and restart it

### ISSUE THREAD

**Issue by flaupretre** [blockwatch-cc/tzindex#7]
Just installed tzindex (extracted binary from the public latest image and inserted in my own base image). Run in a statefulset in Kubernetes cluster. If I stop and restart the pod, tzindex refuses to restart.

Here are the logs 

2019/11/09 15:48:04.836801 INFO MAIN Using configuration file /app/config.json
2019/11/09 15:48:04.836837 INFO MAIN Blockwatch tzindex v005-7-gf124983 -- f124983
2019/11/09 15:48:04.836840 INFO MAIN (c) Copyright 2018-2019 -- KIDTSUNAMI UG
2019/11/09 15:48:04.836843 INFO MAIN Starting Blockwatch-tzindex/v005-7-gf124983.f124983 on 8 cores
2019/11/09 15:48:04.936929 INFO MAIN Profiling mutex/blocking at 1.00% sample rate.
2019/11/09 15:48:04.936982 INFO MAIN Using bolt database /data/db/xtz
2019/11/09 15:48:04.938352 DEBG DATA Statedb database opened successfully.
2019/11/09 15:48:04.938504 INFO BLOC Initializing blockchain crawler in sync mode.
2019/11/09 15:48:04.938937 INFO BLOC Initializing account index.
2019/11/09 15:48:04.940115 DEBG DATA Account database opened successfully.
2019/11/09 15:48:04.940152 DEBG DATA Opening table account with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:4, FillLevel:0}
2019/11/09 15:48:04.940459 DEBG DATA pack: account table loaded journal with 0 entries
2019/11/09 15:48:04.940469 DEBG DATA pack: account table loaded tombstone with 0 entries
2019/11/09 15:48:04.940473 DEBG DATA pack: account table loading package headers from bucket
2019/11/09 15:48:04.940478 DEBG DATA pack: account table loaded 0 package headers
2019/11/09 15:48:04.940485 DEBG DATA Opening account_hash index with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:8, FillLevel:0}
2019/11/09 15:48:04.940503 DEBG DATA pack: loaded account_hash_index/ index journal with 0 entries
2019/11/09 15:48:04.940515 DEBG DATA pack: index account_hash_index/ loaded tombstone with 0 entries
2019/11/09 15:48:04.940520 DEBG DATA pack: account_hash_index/ index loading package headers from bucket
2019/11/09 15:48:04.940525 DEBG DATA pack: account_hash_index/ index loaded 0 package headers
2019/11/09 15:48:04.940535 INFO BLOC Initializing contract index.
2019/11/09 15:48:04.941792 DEBG DATA Contract database opened successfully.
2019/11/09 15:48:04.941814 DEBG DATA Opening table contract with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:10, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.941895 DEBG DATA pack: contract table loaded journal with 0 entries
2019/11/09 15:48:04.941902 DEBG DATA pack: contract table loaded tombstone with 0 entries
2019/11/09 15:48:04.941905 DEBG DATA pack: contract table loading package headers from bucket
2019/11/09 15:48:04.941909 DEBG DATA pack: contract table loaded 0 package headers
2019/11/09 15:48:04.941913 DEBG DATA Opening contract_hash index with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.941923 DEBG DATA pack: loaded contract_hash_index/ index journal with 0 entries
2019/11/09 15:48:04.941931 DEBG DATA pack: index contract_hash_index/ loaded tombstone with 0 entries
2019/11/09 15:48:04.941934 DEBG DATA pack: contract_hash_index/ index loading package headers from bucket
2019/11/09 15:48:04.941937 DEBG DATA pack: contract_hash_index/ index loaded 0 package headers
2019/11/09 15:48:04.941943 INFO BLOC Initializing block index.
2019/11/09 15:48:04.943051 DEBG DATA Block database opened successfully.
2019/11/09 15:48:04.943070 DEBG DATA Opening table block with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:8, FillLevel:0}
2019/11/09 15:48:04.943257 DEBG DATA pack: block table loaded journal with 0 entries
2019/11/09 15:48:04.943265 DEBG DATA pack: block table loaded tombstone with 0 entries
2019/11/09 15:48:04.943268 DEBG DATA pack: block table loading package headers from bucket
2019/11/09 15:48:04.943272 DEBG DATA pack: block table loaded 0 package headers
2019/11/09 15:48:04.943280 DEBG DATA Opening block_hash index with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:64, FillLevel:0}
2019/11/09 15:48:04.943290 DEBG DATA pack: loaded block_hash_index/ index journal with 0 entries
2019/11/09 15:48:04.943295 DEBG DATA pack: index block_hash_index/ loaded tombstone with 0 entries
2019/11/09 15:48:04.943298 DEBG DATA pack: block_hash_index/ index loading package headers from bucket
2019/11/09 15:48:04.943301 DEBG DATA pack: block_hash_index/ index loaded 0 package headers
2019/11/09 15:48:04.943305 INFO BLOC Initializing op index.
2019/11/09 15:48:04.944823 DEBG DATA Op database opened successfully.
2019/11/09 15:48:04.944848 DEBG DATA Opening table op with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:4, FillLevel:0}
2019/11/09 15:48:04.945026 DEBG DATA pack: op table loaded journal with 0 entries
2019/11/09 15:48:04.945037 DEBG DATA pack: op table loaded tombstone with 0 entries
2019/11/09 15:48:04.945040 DEBG DATA pack: op table loading package headers from bucket
2019/11/09 15:48:04.945108 DEBG DATA pack: op table loaded 5 package headers
2019/11/09 15:48:04.945118 DEBG DATA Opening op_hash index with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:128, FillLevel:0}
2019/11/09 15:48:04.945134 DEBG DATA pack: loaded op_hash_index/ index journal with 0 entries
2019/11/09 15:48:04.945140 DEBG DATA pack: index op_hash_index/ loaded tombstone with 0 entries
2019/11/09 15:48:04.945143 DEBG DATA pack: op_hash_index/ index loading package headers from bucket
2019/11/09 15:48:04.945155 DEBG DATA pack: op_hash_index/ index loaded 5 package headers
2019/11/09 15:48:04.945163 INFO BLOC Initializing flow index.
2019/11/09 15:48:04.946316 DEBG DATA Flow database opened successfully.
2019/11/09 15:48:04.946343 DEBG DATA Opening table flow with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:4, FillLevel:0}
2019/11/09 15:48:04.946428 DEBG DATA pack: flow table loaded journal with 0 entries
2019/11/09 15:48:04.946443 DEBG DATA pack: flow table loaded tombstone with 0 entries
2019/11/09 15:48:04.946446 DEBG DATA pack: flow table loading package headers from bucket
2019/11/09 15:48:04.946483 DEBG DATA pack: flow table loaded 9 package headers
2019/11/09 15:48:04.946491 INFO BLOC Initializing chain index.
2019/11/09 15:48:04.947794 DEBG DATA Chain database opened successfully.
2019/11/09 15:48:04.947814 DEBG DATA Opening table chain with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.947968 DEBG DATA pack: chain table loaded journal with 0 entries
2019/11/09 15:48:04.947978 DEBG DATA pack: chain table loaded tombstone with 0 entries
2019/11/09 15:48:04.947981 DEBG DATA pack: chain table loading package headers from bucket
2019/11/09 15:48:04.947984 DEBG DATA pack: chain table loaded 0 package headers
2019/11/09 15:48:04.947989 INFO BLOC Initializing supply index.
2019/11/09 15:48:04.949185 DEBG DATA Supply database opened successfully.
2019/11/09 15:48:04.949208 DEBG DATA Opening table supply with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.949331 DEBG DATA pack: supply table loaded journal with 0 entries
2019/11/09 15:48:04.949344 DEBG DATA pack: supply table loaded tombstone with 0 entries
2019/11/09 15:48:04.949349 DEBG DATA pack: supply table loading package headers from bucket
2019/11/09 15:48:04.949355 DEBG DATA pack: supply table loaded 0 package headers
2019/11/09 15:48:04.949360 INFO BLOC Initializing rights index.
2019/11/09 15:48:04.950686 DEBG DATA Rights database opened successfully.
2019/11/09 15:48:04.950713 DEBG DATA Opening table rights with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:16, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.950775 DEBG DATA pack: rights table loaded journal with 0 entries
2019/11/09 15:48:04.950783 DEBG DATA pack: rights table loaded tombstone with 0 entries
2019/11/09 15:48:04.950786 DEBG DATA pack: rights table loading package headers from bucket
2019/11/09 15:48:04.951032 DEBG DATA pack: rights table loaded 132 package headers
2019/11/09 15:48:04.951043 INFO BLOC Initializing snapshot index.
2019/11/09 15:48:04.952435 DEBG DATA Snapshot database opened successfully.
2019/11/09 15:48:04.952456 DEBG DATA Opening table snapshot with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:17, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.952532 DEBG DATA pack: snapshot table loaded journal with 0 entries
2019/11/09 15:48:04.952540 DEBG DATA pack: snapshot table loaded tombstone with 0 entries
2019/11/09 15:48:04.952543 DEBG DATA pack: snapshot table loading package headers from bucket
2019/11/09 15:48:04.952562 DEBG DATA pack: snapshot table loaded 5 package headers
2019/11/09 15:48:04.952567 INFO BLOC Initializing income index.
2019/11/09 15:48:04.953749 DEBG DATA Income database opened successfully.
2019/11/09 15:48:04.953768 DEBG DATA Opening table income with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:17, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.953898 DEBG DATA pack: income table loaded journal with 0 entries
2019/11/09 15:48:04.953909 DEBG DATA pack: income table loaded tombstone with 0 entries
2019/11/09 15:48:04.953912 DEBG DATA pack: income table loading package headers from bucket
2019/11/09 15:48:04.953919 DEBG DATA pack: income table loaded 0 package headers
2019/11/09 15:48:04.953923 INFO BLOC Initializing gov index.
2019/11/09 15:48:04.955021 DEBG DATA Gov database opened successfully.
2019/11/09 15:48:04.955039 DEBG DATA Opening table election with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.955599 DEBG DATA pack: election table loaded journal with 0 entries
2019/11/09 15:48:04.955612 DEBG DATA pack: election table loaded tombstone with 0 entries
2019/11/09 15:48:04.955769 DEBG DATA pack: election table loading package headers from bucket
2019/11/09 15:48:04.955858 DEBG DATA pack: election table loaded 0 package headers
2019/11/09 15:48:04.955895 DEBG DATA Opening table proposal with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.956176 DEBG DATA pack: proposal table loaded journal with 0 entries
2019/11/09 15:48:04.956185 DEBG DATA pack: proposal table loaded tombstone with 0 entries
2019/11/09 15:48:04.956189 DEBG DATA pack: proposal table loading package headers from bucket
2019/11/09 15:48:04.956194 DEBG DATA pack: proposal table loaded 0 package headers
2019/11/09 15:48:04.956200 DEBG DATA Opening table vote with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.956312 DEBG DATA pack: vote table loaded journal with 0 entries
2019/11/09 15:48:04.956324 DEBG DATA pack: vote table loaded tombstone with 0 entries
2019/11/09 15:48:04.956328 DEBG DATA pack: vote table loading package headers from bucket
2019/11/09 15:48:04.956333 DEBG DATA pack: vote table loaded 0 package headers
2019/11/09 15:48:04.956339 DEBG DATA Opening table ballot with opts pack.Options{PackSizeLog2:0, JournalSizeLog2:15, CacheSize:2, FillLevel:0}
2019/11/09 15:48:04.956389 DEBG DATA pack: ballot table loaded journal with 0 entries
2019/11/09 15:48:04.956397 DEBG DATA pack: ballot table loaded tombstone with 0 entries
2019/11/09 15:48:04.956400 DEBG DATA pack: ballot table loading package headers from bucket
2019/11/09 15:48:04.956404 DEBG DATA pack: ballot table loaded 0 package headers
2019/11/09 15:48:04.956422 INFO BLOC Initializing report manager.
2019/11/09 15:48:04.958555 DEBG DATA Reports database opened successfully.
2019/11/09 15:48:04.959699 DEBG DATA Opening table supply_stats with opts pack.Options{PackSizeLog2:12, JournalSizeLog2:10, CacheSize:2, FillLevel:100}
2019/11/09 15:48:04.959822 DEBG DATA pack: supply_stats table loaded journal with 0 entries
2019/11/09 15:48:04.959832 DEBG DATA pack: supply_stats table loaded tombstone with 0 entries
2019/11/09 15:48:04.959837 DEBG DATA pack: supply_stats table loading package headers from bucket
2019/11/09 15:48:04.959843 DEBG DATA pack: supply_stats table loaded 0 package headers
2019/11/09 15:48:04.960988 DEBG DATA Opening table activity with opts pack.Options{PackSizeLog2:12, JournalSizeLog2:10, CacheSize:2, FillLevel:100}
2019/11/09 15:48:04.961086 DEBG DATA pack: activity table loaded journal with 0 entries
2019/11/09 15:48:04.961094 DEBG DATA pack: activity table loaded tombstone with 0 entries
2019/11/09 15:48:04.961097 DEBG DATA pack: activity table loading package headers from bucket
2019/11/09 15:48:04.961100 DEBG DATA pack: activity table loaded 0 package headers
2019/11/09 15:48:04.962122 DEBG DATA Opening table age with opts pack.Options{PackSizeLog2:12, JournalSizeLog2:10, CacheSize:2, FillLevel:100}
2019/11/09 15:48:04.962161 DEBG DATA pack: age table loaded journal with 0 entries
2019/11/09 15:48:04.962169 DEBG DATA pack: age table loaded tombstone with 0 entries
2019/11/09 15:48:04.962172 DEBG DATA pack: age table loading package headers from bucket
2019/11/09 15:48:04.962175 DEBG DATA pack: age table loaded 0 package headers
2019/11/09 15:48:04.963251 DEBG DATA Opening table balance with opts pack.Options{PackSizeLog2:12, JournalSizeLog2:10, CacheSize:2, FillLevel:100}
2019/11/09 15:48:04.963504 DEBG DATA pack: balance table loaded journal with 0 entries
2019/11/09 15:48:04.963520 DEBG DATA pack: balance table loaded tombstone with 0 entries
2019/11/09 15:48:04.963523 DEBG DATA pack: balance table loading package headers from bucket
2019/11/09 15:48:04.963527 DEBG DATA pack: balance table loaded 0 package headers
2019/11/09 15:48:04.964546 DEBG DATA Opening table op_stats with opts pack.Options{PackSizeLog2:12, JournalSizeLog2:10, CacheSize:2, FillLevel:100}
2019/11/09 15:48:04.964599 DEBG DATA pack: op_stats table loaded journal with 0 entries
2019/11/09 15:48:04.964610 DEBG DATA pack: op_stats table loaded tombstone with 0 entries
2019/11/09 15:48:04.964614 DEBG DATA pack: op_stats table loading package headers from bucket
2019/11/09 15:48:04.964618 DEBG DATA pack: op_stats table loaded 0 package headers
2019/11/09 15:48:04.965645 INFO BLOC Connecting to RPC server.
2019/11/09 15:48:04.965709 DEBG JRPC GET /chains/main/blocks/head/header HTTP/1.1
Host: service-node-rpc:8732
Accept: application/json
Content-Type: application/json
User-Agent: Blockwatch-tzindex/v005-7-gf124983.f124983

2019/11/09 15:48:04.968029 DEBG JRPC HTTP/1.1 200 OK
Content-Length: 645
Content-Type: application/json

{"protocol":"PsBabyM1eUXZseaJdmXFApDSBqj8YBfwELoxZHHW77EMcAbbwAS","chain_id":"NetXdQprcVkpaWU","hash":"BKqDmsepj88WA5JYDe27bN4RG99vDNxvWhHSp4v4Ljr4yGJ8XcL","
level":686616,"proto":5,"predecessor":"BLgZRxvoMnLzTCNtkLcgg28bERPmPrpw2ofS51X5tke7vyZR8M5","timestamp":"2019-11-09T15:47:04Z","validation_pass":4,"operation
s_hash":"LLoZqvdXwfMToqVy3EwwgKtGTiTq9rsUecF24aMeK2QB3MryhuktY","fitness":["01","0000000000007a18"],"context":"CoWUKHsgdgJRf1HiaDkPKmfQDUuTEvsUWvA4PtDRfNXPsy
6e9LUu","priority":0,"proof_of_work_nonce":"12fe0a23baf80100","signature":"sigaWs7ry5UZxzBeqkBLXcRgCi64YKG1eXLrjfvfBEcoKvEuKYDAK8zjAEGWFbPRCFFkMWRPfop8c4hJDa
q5bmeotg1HvVDn"}
2019/11/09 15:48:04.968494 INFO BLOC Crawling Tezos Mainnet.
2019/11/09 15:48:04.968557 TRCE DATA query: block table non-indexed field 'h' for cond 0, fallback to table scan
2019/11/09 15:48:04.968568 TRCE DATA query: block table non-indexed field 'Z' for cond 1, fallback to table scan
2019/11/09 15:48:04.968587 INFO BLOC Stopping report manager.
2019/11/09 15:48:04.969786 DEBG DATA pack: closing supply_stats table with 0/0 records
2019/11/09 15:48:04.970834 DEBG DATA pack: closing activity table with 0/0 records
2019/11/09 15:48:04.971963 DEBG DATA pack: closing age table with 0/0 records
2019/11/09 15:48:04.973031 DEBG DATA pack: closing balance table with 0/0 records
2019/11/09 15:48:04.973996 DEBG DATA pack: closing op_stats table with 0/0 records
2019/11/09 15:48:04.976109 DEBG DATA Reports database closed successfully.
2019/11/09 15:48:04.976118 INFO BLOC Stopped report manager.
2019/11/09 15:48:04.976122 INFO BLOC Closing account index.
2019/11/09 15:48:04.976126 DEBG DATA pack: closing account table with 0/0 records
2019/11/09 15:48:04.976145 DEBG DATA pack: closing hash index account_hash_index/ with 0/0 records
2019/11/09 15:48:04.978926 DEBG DATA Account database closed successfully.
2019/11/09 15:48:04.978935 DEBG BLOC Storing account idx tip.
2019/11/09 15:48:04.980032 INFO BLOC Closing contract index.
2019/11/09 15:48:04.980040 DEBG DATA pack: closing contract table with 0/0 records
2019/11/09 15:48:04.980053 DEBG DATA pack: closing hash index contract_hash_index/ with 0/0 records
2019/11/09 15:48:04.982404 DEBG DATA Contract database closed successfully.
2019/11/09 15:48:04.982412 DEBG BLOC Storing contract idx tip.
2019/11/09 15:48:04.983395 INFO BLOC Closing block index.
2019/11/09 15:48:04.983403 DEBG DATA pack: closing block table with 0/0 records
2019/11/09 15:48:04.983417 DEBG DATA pack: closing hash index block_hash_index/ with 0/0 records
2019/11/09 15:48:04.986466 DEBG DATA Block database closed successfully.
2019/11/09 15:48:04.986475 DEBG BLOC Storing block idx tip.
2019/11/09 15:48:04.987491 INFO BLOC Closing op index.
2019/11/09 15:48:04.987500 DEBG DATA pack: closing op table with 0/0 records
2019/11/09 15:48:04.987513 DEBG DATA pack: closing hash index op_hash_index/ with 0/0 records
2019/11/09 15:48:04.990936 DEBG DATA Op database closed successfully.
2019/11/09 15:48:04.990944 DEBG BLOC Storing op idx tip.
2019/11/09 15:48:04.992021 INFO BLOC Closing flow index.
2019/11/09 15:48:04.992029 DEBG DATA pack: closing flow table with 0/0 records
2019/11/09 15:48:04.994190 DEBG DATA Flow database closed successfully.
2019/11/09 15:48:04.994198 DEBG BLOC Storing flow idx tip.
2019/11/09 15:48:04.995339 INFO BLOC Closing chain index.
2019/11/09 15:48:04.995348 DEBG DATA pack: closing chain table with 0/0 records
2019/11/09 15:48:04.997406 DEBG DATA Chain database closed successfully.
2019/11/09 15:48:04.997414 DEBG BLOC Storing chain idx tip.
2019/11/09 15:48:04.998493 INFO BLOC Closing supply index.
2019/11/09 15:48:04.998500 DEBG DATA pack: closing supply table with 0/0 records
2019/11/09 15:48:05.000729 DEBG DATA Supply database closed successfully.
2019/11/09 15:48:05.000738 DEBG BLOC Storing supply idx tip.
2019/11/09 15:48:05.001813 INFO BLOC Closing rights index.
2019/11/09 15:48:05.001821 DEBG DATA pack: closing rights table with 0/0 records
2019/11/09 15:48:05.004171 DEBG DATA Rights database closed successfully.
2019/11/09 15:48:05.004179 DEBG BLOC Storing rights idx tip.
2019/11/09 15:48:05.005318 INFO BLOC Closing snapshot index.
2019/11/09 15:48:05.005329 DEBG DATA pack: closing snapshot table with 0/0 records
2019/11/09 15:48:05.007532 DEBG DATA Snapshot database closed successfully.
2019/11/09 15:48:05.007541 DEBG BLOC Storing snapshot idx tip.
2019/11/09 15:48:05.008718 INFO BLOC Closing income index.
2019/11/09 15:48:05.008727 DEBG DATA pack: closing income table with 0/0 records
2019/11/09 15:48:05.010899 DEBG DATA Income database closed successfully.
2019/11/09 15:48:05.010907 DEBG BLOC Storing income idx tip.
2019/11/09 15:48:05.012018 INFO BLOC Closing gov index.
2019/11/09 15:48:05.012025 DEBG DATA pack: closing election table with 0/0 records
2019/11/09 15:48:05.013021 DEBG DATA pack: closing proposal table with 0/0 records
2019/11/09 15:48:05.014157 DEBG DATA pack: closing vote table with 0/0 records
2019/11/09 15:48:05.015145 DEBG DATA pack: closing ballot table with 0/0 records
2019/11/09 15:48:05.017406 DEBG DATA Gov database closed successfully.
2019/11/09 15:48:05.017415 DEBG BLOC Storing gov idx tip.
2019/11/09 15:48:05.019661 DEBG DATA Statedb database closed successfully.
2019/11/09 15:48:05.019671 Fatal: error initializing crawler: block not indexed

So, if the base is corrupted, how can it be shutdown without getting corrupted? And is there a mechanism to clean the database before starting tzindex ?

Thanks

**Comment by echa** [comment]
The `block not indexed` error is an indication of an inconsistent database state. This happens on unclean shutdown and in rare circumstances when the indexer experiences an internal error when in the middle of indexing a block.

What I usually do to prevent this is setting a `stop_grace_period`. Shutdown is usually fast (a second or two) unless you have open http connections, then its defined by `server.shutdown_timeout` in the config (defaults to 15sec). So anything beyond 20-30 sec should be safe.

When the database is corrupted, there's no easy way to repair it right now (an fsck like command is not implemented yet). The only solution is to remove all database files and reindex from scratch.

To prevent wait times you can do database snapshots. Right now I advice to stop the indexer and copy all database files manually. A life snapshot feature exists, but is not production ready yet.

**Comment by flaupretre** [comment]
Hi, thanks for your quick reply. According to the kubernetes documentation, especially with a terminationGracePeriod, it should send a SIGTERM and wait for a graceful shutdown. Actually, if I watch the logs, the connection is closed without displaying any message indicating a graceful shutdown. Everything indicates that the processes are destroyed with a SIGKILL without receiving a gentle SIGTERM before. That's strange.

Anyway, I solved the problem with the addition of a 'preStop' script which just sends a SIGTERM to the tzindex process. With this script, the database is never corrupted.

For backups, as it is deployed on AWS/EKS, I will implement something based on EBS snapshots, as long as you don't provide the possibility to backup/snapshot without stopping the program.

**Comment by echa** [comment]
EBS snapshots may or may not work. The database files are mmapped and new data gets flushed after each block is processed, but sometimes also during block processing when database journals run full. When a filesystem snapshot runs during block processing the database state may be currupted because some database files may already be updated from journal flush, may be in the middle of a journal flush or are not flushed yet. It's similar to Postgres or other databases where you get no guarantee about data consistency on the fs layer.

The not-production-ready feature for snapshotting might actually be better. Call `PUT /system/snapshot` (with an empty body) which makes the indexer copy consistent db files to a subdirectory inside the snapshot directory (see config `crawler.snapshot_path`). 

The missing pice on this feature is that it's not mutually exclusive with block processing right now. I'll push this feature a bit up the priority stack. Are you on a commercial license or do you use OSS?

**Comment by flaupretre** [comment]
I'm currently testing tzindex for a potential commercial license. I am working for the Ledger company and we are implementing a platform to support the tezos coin on our hardware/software. Nothing is decided yet and that's why I'm currently testing 'infrastructure' aspects of different tezos indexers (mostly backup/restore and monitoring).

When I was talking about EBS snapshots, I was talking of cold snapshots, after a graceful shutdown of the indexer. Apart from snapshots (I will try this too), it seems to be the only way to guarantee DB consistency. Even if the database is rather fast to regenerate, it takes hours and we'll need a few backups (maybe 4~5 daily snapshots). Hot snapshots are interesting, and I'll try it, but they will need to be transferred to an external location (S3 for instance).

**Comment by echa** [comment]
A faster way (50min on mainet currently) is to use the RPC proxy that comes with the pro version. Even with a regular node it should be sufficient to do one snapshot a day or even one a week. Catching up the 1440 blocks a day is rather fast in my experience.

As for hot snapshots, you can orchestrate them with the `PUT /system/snapshot` call which is synchronous (blocks until done and then returns a 204 unless you set a very short HTTP write timeout and have very slow storage). You can configure snapshot directory and the indexer will create a subdir with the current height, but you'd still have to run the S3 copy when done.
